<?php

namespace common\onecms;

use common\models\Post;
use yii\base\Widget;

class PartnerWidget extends Widget
{
  public function init() {
    parent::init(); // TODO: Change the autogenerated stub
  }

  public function run() {
    parent::run(); // TODO: Change the autogenerated stub
    $post = new Post();
    $dataPartner = $post->find('image')->where(['category_id' => 18])->all();
    return $this->render('widget/partner', [
      'nodes' => $dataPartner
    ]);
  }
}